### ISSUE TITLE
undefined method error

### ISSUE THREAD

**Issue by mago0** [jgoulah/knife-env-diff#2]
DEBUG: Using configuration from /Users/redacted/.chef/knife.rb
DEBUG: Signing the request as workstation
DEBUG: Sending HTTP Request via GET to redacted:4000/environments/staging/cookbooks
DEBUG: Signing the request as workstation
DEBUG: Sending HTTP Request via GET to redacted:4000/environments/production/cookbooks
diffing environment staging against production

/Library/Ruby/Gems/1.8/gems/knife-env-diff-0.0.3/lib/chef/knife/env-diff.rb:51:in `run': undefined method`[]' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/1.8/gems/knife-env-diff-0.0.3/lib/chef/knife/env-diff.rb:50:in `each'
    from /Library/Ruby/Gems/1.8/gems/knife-env-diff-0.0.3/lib/chef/knife/env-diff.rb:50:in`run'
    from /Library/Ruby/Gems/1.8/gems/knife-env-diff-0.0.3/lib/chef/knife/env-diff.rb:45:in `each'
    from /Library/Ruby/Gems/1.8/gems/knife-env-diff-0.0.3/lib/chef/knife/env-diff.rb:45:in`run'
    from /Library/Ruby/Gems/1.8/gems/knife-env-diff-0.0.3/lib/chef/knife/env-diff.rb:44:in `each_value'
    from /Library/Ruby/Gems/1.8/gems/knife-env-diff-0.0.3/lib/chef/knife/env-diff.rb:44:in`run'
    from /Library/Ruby/Gems/1.8/gems/chef-10.12.0/lib/chef/knife.rb:402:in `run_with_pretty_exceptions'
    from /Library/Ruby/Gems/1.8/gems/chef-10.12.0/lib/chef/knife.rb:168:in`run'
    from /Library/Ruby/Gems/1.8/gems/chef-10.12.0/lib/chef/application/knife.rb:123:in `run'
    from /Library/Ruby/Gems/1.8/gems/chef-10.12.0/bin/knife:25
    from /usr/bin/knife:19:in`load'
    from /usr/bin/knife:19

**Comment by svanzoest** [comment]
I am seeing this too. Is this because it assumes that every environment has all cookbooks pinned?

**Comment by jgoulah** [comment]
should not be the case,  we have a "testing" environment that is entirely unconstrained and it works fine.   @svanzoest are you also using an older (1.8.x) ruby?   I can't reproduce this problem but I've only tested on 1.9.x

**Comment by svanzoest** [comment]
Yes. Ruby 1.8.7 I believe. I can get specifics when I get to the office.

**Comment by jgoulah** [comment]
ok i can reproduce on 1.8.7  -- you really shouldn't use such an old ruby with chef, but I will take a look anyway

**Comment by svanzoest** [comment]
We are in the process of migrating to 1.9, however, the default ruby on Ubuntu 12.04.1 (precise) is
ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux] with chef installed via debian packages from apt.opscode.com
